<?php

/**
 * Implementation of hook_menu()
 */
function dis_permits_menu() {

    $items = array();

	$items['add-associate-inward-permit'] = array(
        'title' => 'Add Associate Inward Permit - Select Company',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_associate_inward_permit_form'),
        'access callback' => 'user_access',
        'access arguments' => array('create associate_inward_permit content'),
        'type' => MENU_CALLBACK,
        'file' => 'dis_permits.menu.inc',
    ); 	

    $items['add-inward-permit'] = array(
        'title' => 'Add Inward Permit - Select Company',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_inward_permit_form'),
        'access callback' => 'user_access',
        'access arguments' => array('create inward_permit content'),
        'type' => MENU_CALLBACK,
        'file' => 'dis_permits.menu.inc',
    );  

    return $items;
}


/**
 * Implementation of hook_form_BASE_FORM_ID_alter()
 */
function dis_permits_form_dispatch_node_form_alter(&$form, &$form_state, $form_id){
   /*
    $a = 1;
    $b = 1;

    if($form['field_permit_required']['und']['#default_value'] == null){
        $form['field_permit_required']['und']['#default_value'] = '1';
    } */
/*
    if($form['field_permit_required']['und']['#default_value'] == '1'){
        $form['field_associate_inward_permit']['und']['#required'] = 1;
        $form['field_associate_inward_permit']['#access'] = 1;
        $form['field_permit_remarks']['und']['#required'] = 0; 
        $form['field_permit_remarks']['#access'] = 0;          
    } else {
        $form['field_associate_inward_permit']['und']['#required'] = 0;
        $form['field_associate_inward_permit']['#access'] = 0;
        $form['field_permit_remarks']['und']['#required'] = 1; 
        $form['field_permit_remarks']['#access'] = 1;  
    }
    $form['field_associate_inward_permit']['und']['#states'] = array(
        'visible' => array(
            ':input[name="field_permit_required"]' => array('value' => 1)
            )

        );

    $form['field_permit_remarks']['und']['#states'] = array(
        'visible' => array(
            ':input[name="field_permit_required"]' => array('value' => 0)
            )

        );
*/
}