<?php
/**
 * @file
 * dis_permits_feature.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function dis_permits_feature_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function dis_permits_feature_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function dis_permits_feature_node_info() {
  $items = array(
    'associate_inward_permit' => array(
      'name' => t('Associate Inward Permit'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'inward_permit' => array(
      'name' => t('Inward Permit'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
